name: Run CI
on: pull_request

jobs:
  ci:
    name: CI Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter version 2.0.0
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
          
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk